Meme generator #13
PEC-CSS/acm-fun pull request #63
Opened 2023-10-24 10:01 UTC by GauravGupta993

#13 Solved. 
Made a new PR because some conflicts were appearing due to which I had to discard the commit that closed the previous PR.

2023-10-24 10:25 UTC, ken1000minus7 requested changes

2023-10-24 10:25 UTC, ken1000minus7 commented on src/pages/activities/RandomMemes.js
> +            <input className="rmeme-text" placeholder="Enter name of community here" id="text" type="text" onChange={GetName}></input>
use a more unique id than `text`, rest lgtm

2023-10-24 11:05 UTC, Ishwarendra requested changes
The input doesn't seem to work. I searched by writing `chess` but it still returned random meme not related to chess in any way

![](https://i.redd.it/csb6xkh3q3wb1.jpg)

Also, there is CLS (Cumulative layout shift), on hovering submit button. You can take inspiration for button from `Random Quote generator` activity.

2023-10-24 11:06 UTC, Ishwarendra commented
> Also, there is CLS (Cumulative layout shift), on hovering submit button. You can take inspiration for button from `Random Quote generator` activity.

By CLS, I mean other `div` move due to increase in size of button. This side-effect is not good.

2023-10-24 15:24 UTC, GauravGupta993 commented
> > Also, there is CLS (Cumulative layout shift), on hovering submit button. You can take inspiration for button from `Random Quote generator` activity.
> 
> By CLS, I mean other `div` move due to increase in size of button. This side-effect is not good.

Ok, will do so. Also, API used searches for memes from posts in Reddit communities. The community name for getting chess memes is r/chessmemes so putting chessmemes in the input box should work. Also, it produces related memes after clicking generate memes after clicking submit. Just after clicking submit it produces meme related to previous topic. To solve this what I can do is not generate any meme on clicking submit and generate meme only when clicking generate meme.

2023-10-26 15:05 UTC, Ishwarendra requested changes
@GauravGupta993 While you are at the cls issue, write in small font about the example.
For example, if user has to type `r/chessmemes` then there should be a text `For example: r/chessmemes` will return chess memes, so that user knows what to type in the box.

2023-10-30 19:00 UTC, Ishwarendra requested changes
Whenever user submits the community name, show it somewhere so user knows which community memes he will be/is getting.

2023-10-30 19:02 UTC, Ishwarendra requested changes
Also add a loader, while the data is getting fetched show some text `Loading...` or some spinner. You can see `Random Quote Generator` Activity for spinner.

2023-10-30 19:03 UTC, Ishwarendra approved these changes

2023-10-30 19:03 UTC, merged