implemented smooth scrolling
PEC-CSS/acm-fun pull request #79
Opened 2024-10-04 17:16 UTC by sp9324

Implemented smooth scrolling. When "Games" button is clicked, library react-scroll creates a smooth scroll effect to the games section. Also changed CSS to match the effect.

https://github.com/user-attachments/assets/dc23c526-3efe-4f7c-8c4f-8c28d905d2ba

2024-10-04 17:48 UTC, ken1000minus7 requested changes

2024-10-04 17:48 UTC, ken1000minus7 commented on src/components/Home/CardItem.js
> +          </ScrollLink>
This is supposed to take the user to the page of the particular game/activity so scroll link is not required here

2024-10-04 17:48 UTC, ken1000minus7 commented on src/pages/Games.js
> +                            <section id={`game-${index}`} key={game.urlTerm} style={{ padding: '50px 0' }}>
Can u remove this padding, it doesn't [look good](https://acm-fun-git-fork-sp9324-master-acm-fun.vercel.app/games)

2024-10-04 17:48 UTC, ken1000minus7 commented on src/pages/Home.js
> +                <h2>Games Section</h2>
The cards below show both games and activities so naming this just games would be incorrect
Also the text is kinda invisible cuz of the background
![image](https://github.com/user-attachments/assets/69cebac8-3c25-4b06-88eb-99bd385624e8)

2024-10-04 17:48 UTC, ken1000minus7 commented on src/components/Home/HeroSection.js
> +        </ScrollLink>
This button is currently doing nothing cuz games and activities are shown together below
You can either direct it to `games-section` as well or separate the cards below into games and activities and link accordingly

2024-10-05 04:47 UTC, sp9324 commented
Closing this issue as the change made is unnecessary.

2024-10-05 04:47 UTC, closed without merging